SalasDeReuniones/SalasDeReuniones/Controllers/EquipoController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace SalasDeReuniones.Controllers
{
    [Authorize]
    public class EquipoController : Controller
    {
        private ProyectoPAEntities context = new ProyectoPAEntities();
        // GET: Equipo
        public ActionResult Index()
        {
            var Equipos = context.equipoes.ToList();
            return View(Equipos);
        }

        [HttpGet]
        public ActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Crear(equipo equipo)
        {
            if (ModelState.IsValid)
            {
                context.equipoes.Add(equipo);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return View(equipo);
        }
        [HttpGet]
        public ActionResult Editar(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            var equipo = context.equipoes.Find(id);
            if (equipo == null)
                return HttpNotFound();

            return View(equipo);
        }

        [HttpPost]
        public ActionResult Editar(equipo equipoes)
        {
            if (ModelState.IsValid)
            {


                context.Entry(equipoes).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(equipoes);
        }

        [HttpGet]
        public ActionResult Eliminar(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            var equipos = context.equipoes.SingleOrDefault(l => l.Id_Equipo == id);
            if (equipos == null)
                return HttpNotFound();
            return View(equipos);

        }
        [HttpPost, ActionName("Eliminar")]
        public ActionResult ConfirmarEliminar(int id)
        {
            var equipos = context.equipoes.Find(id);
            context.equipoes.Remove(equipos);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SalasDeReuniones/SalasDeReuniones/Controllers/SalaController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SalasDeReuniones.Controllers
{
    [Authorize]
    public class SalaController : Controller
    {
        private ProyectoPAEntities context = new ProyectoPAEntities();
        // GET: Sala
        public ActionResult Index()
        {
            var Salas = context.salas.ToList();
            
            return View(Salas);
        }
       
        [HttpGet]
        public ActionResult Crear()
        {
            
            ViewBag.EquipoId = new SelectList(context.equipoes, "Id_Equipo", "nombre_equipo");
            return View();
        }

        [HttpPost]
        public ActionResult Crear(sala sala, List<int> EquipoId)
        {
            if (ModelState.IsValid)
            {
                context.salas.Add(sala);
                if (EquipoId != null)
                {
                    foreach (var equipoId in EquipoId)
                    {
                        context.equipo_salas.Add(new equipo_salas { IdSala = sala.IdSala, Id_Equipo = equipoId });
                    }
                }
                
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EquipoId = new SelectList(context.equipoes, "Id_Equipo", "nombre_equipo");
            return View(sala);
        }

        [HttpGet]
        public ActionResult Editar(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            var sala = context.salas.Find(id);
            if (sala == null)
                return HttpNotFound();
            ViewBag.EquipoId = new SelectList(context.equipoes, "Id_Equipo", "nombre_equipo");
            return View(sala);
        }

        [HttpPost]
        public ActionResult Editar(sala sala,List<int> EquipoId)
        {
            if (ModelState.IsValid)
            {
                context.Entry(sala).State = EntityState.Modified;
                int salaId = sala.IdSala;
                var equipo_salas = context.equipo_salas.ToList();
                if (EquipoId != null)
                {
                    foreach (var equipo in context.equipo_salas)
                    {
                        if (equipo.IdSala == salaId)
                        {
                            context.equipo_salas.Remove(equipo);

                        }
                    }
                    foreach (var equipoId in EquipoId)
                    {
                        context.equipo_salas.Add(new equipo_salas { IdSala = salaId, Id_Equipo = equipoId });
                    }
                }
                else
                {
                    foreach (var equipo in context.equipo_salas)
                    {
                        if (equipo.IdSala == salaId)
                        {
                            context.equipo_salas.Remove(equipo);

                        }
                    }
                }
                
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EquipoId = new SelectList(context.equipoes, "Id_Equipo", "nombre_equipo");
            return View(sala);
        }

        [HttpGet]
        public ActionResult Eliminar(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            var sala = context.salas.SingleOrDefault(l => l.IdSala == id);
            if (sala == null)
                return HttpNotFound();
            return View(sala);
        }

        [HttpPost, ActionName("Eliminar")]
        public ActionResult ConfirmarEliminar(int? id)
        {
            var sala = context.salas.Find(id);
            context.salas.Remove(sala);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SalasDeReuniones/SalasDeReuniones/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Salas El Mejor</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark custom-nav">
        <div class="container d-flex justify-content-center w-100">
            <!-- Centrado de la barra -->
            @Html.ActionLink("Salas El Mejor", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-center w-100">
                <!-- Centrado del contenido -->
                <ul class="navbar-nav flex-grow-1 justify-content-center">
                    <!-- Centrado de los enlaces -->
                    @if (User.IsInRole("Administrador"))
                    {
                        <li>@Html.ActionLink("Salas", "Index", "Sala", new { area = "" }, new { @class = "nav-link" })</li>
                    }

                    @if (User.IsInRole("Administrador"))
                    {
                        <li>@Html.ActionLink("Equipo de Salas", "Index", "Equipo", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                    @if (User.IsInRole("Administrador"))
                    {
                        <li>@Html.ActionLink("Estadisticas", "Dashboard", "Estadisticas", new { area = "" }, new { @class = "nav-link" })</li>
                    }

                    <li>@Html.ActionLink("Reservas", "Index", "Reservas", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>

                <!-- Dropdown del perfil de usuario -->
                <ul class="navbar-nav ml-auto">
                    @if (Session["UsuarioId"] != null)
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Bienvenido, @Session["UsuarioNombre"]
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                                <li>
                                    @Html.ActionLink("Cerrar sesión", "Logout", "Usuario", null, new { @class = "dropdown-item" })
                                </li>
                            </ul>
                        </li>
                    }
                    else if (!(ViewContext.RouteData.Values["controller"].ToString() == "Usuario" &&
                    ViewContext.RouteData.Values["action"].ToString() == "Login"))
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Iniciar sesión", "Login", "Usuario", null, new { @class = "nav-link" })
                        </li>
                    }
                </ul>

            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Todo los derechos Reservados Salas El Mejor</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>


<style>
    .custom-nav {
        background-color: #1f618d; /* Cambia este color por el que quieras /
    color: #ffffff; / Cambia el color del texto si es necesario */
    }

</style>